CREATE TABLE history (
  historyId int(11) NOT NULL AUTO_INCREMENT,
  userName varchar(40) NOT NULL,
  productId varchar(32) NOT NULL,
  seeTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (historyId),
  CONSTRAINT userNameInHistory FOREIGN KEY (userName) REFERENCES user (userName) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT productIdInHistory FOREIGN KEY (productId) REFERENCES product (productId) ON DELETE CASCADE ON UPDATE CASCADE
)